name: RaeMarie Donaldson
owner: RaeMarie Donaldson

baseurl: "/portfolio-website/" # the base url of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:title

collections:
  projects:
    output: true

exclude:
  - LICENSE
  - README.md
  - html-templates
